// source-angular/src/app/form/form.component.ts
import { Component } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { CommonModule } from '@angular/common'
import dayjs from 'dayjs'

type FormValuesType = {
  loanAccount: string
  checking: null | string
  debitCard: null | string
  routing: string
  bankAccount: string
  confirmBankAccount: string
  card: string
  nameOnCard: string
  expirationDate: string
  cvv: string
}

@Component({
  selector: 'app-form',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './form.component.html',
  styleUrl: './form.component.css'
})
export class FormComponent {
  title = 'form'
  formValues: FormValuesType = {
    loanAccount: '',
    checking: 'true',
    debitCard: null,
    routing: '',
    bankAccount: '',
    confirmBankAccount: '',
    card: '',
    nameOnCard: '',
    expirationDate: '',
    cvv: ''
  }

  public get isFormValid(): boolean {
    if (this.formValues.checking === 'true') {
      return (
        this.formValues.loanAccount.length === 10 &&
        this.formValues.routing.length === 9 &&
        this.formValues.bankAccount.length === 10 &&
        this.formValues.confirmBankAccount.length === 10
      )
    }
    return (
      this.formValues.loanAccount.length === 10 &&
      this.formValues.card.length === 16 &&
      this.formValues.nameOnCard.length > 1 &&
      dayjs(this.formValues.expirationDate, 'MM/YY').isValid() &&
      this.formValues.cvv.length === 3
    )
  }

  public setAccountType(accountType: string) {
    if (accountType === 'checking') {
      this.formValues.checking = 'true'
      this.formValues.debitCard = null
    } else {
      this.formValues.checking = null
      this.formValues.debitCard = 'true'
    }
  }

  onSubmit() {
    console.log('Form submitted:', this.formValues)
    if (this.isFormValid) {
      console.log('Form submitted successfully!')
    } else {
      console.log('Form is invalid!')
    }
  }
}

<div class="Form">
  <h2>One-time Loan Payment</h2>
  <p>Fill out the form below to complete your payment.</p>
  <!-- formValues: {{ formValues | json }} -->
  <!-- <br />
  isChecking: {{ isChecking }}
  <br />
  isDebitCard: {{ isDebitCard }} -->
  <form>
    <div class="field">
      <label for="loanAccount"> Loan Account Number </label>
      <input
        type="number"
        name="loanAccount"
        #loanAccount="ngModel"
        [(ngModel)]="formValues.loanAccount"
        min="1000000000"
        max="9999999999"
        required
      />
      <!-- <br />touched: {{ loanAccount.touched }} <br />dirty: {{ loanAccount.dirty }} <br />errors:
      {{ loanAccount.errors | json }}<br /> -->
      <div *ngIf="loanAccount.touched || loanAccount.dirty">
        <span *ngIf="loanAccount.touched && loanAccount.errors?.['required']">
          Loan Account Number is required
        </span>
        <span *ngIf="loanAccount.touched && loanAccount.errors?.['min']">
          Valid Loan Account Number is 10 digits
        </span>
      </div>
    </div>
    <div class="split-container">
      <div class="split-left">
        <div class="field">
          <label for="accountType">Type of Account</label>
          <div class="radio-group">
            <div (click)="setAccountType('checking')">
              <input
                type="radio"
                name="checking"
                #checking="ngModel"
                [(ngModel)]="formValues.checking"
                [value]="formValues.checking === 'true' ? 'true' : 'false'"
              />
              <label for="checking">Checking</label>
            </div>
            <div (click)="setAccountType('debitCard')">
              <input
                type="radio"
                name="debitCard"
                #debitCard="ngModel"
                [(ngModel)]="formValues.debitCard"
                [value]="formValues.debitCard === 'true' ? 'true' : 'false'"
              />
              <label for="debitCard">Debit Card</label>
            </div>
          </div>
        </div>
        <div *ngIf="formValues.checking">
          <div class="field">
            <label for="routing" class="{setLabelClassName(routingError)}"> Routing Number </label>
            <input
              type="number"
              name="routing"
              #routing="ngModel"
              [(ngModel)]="formValues.routing"
              minlength="9"
              maxlength="9"
            />
            <div *ngIf="routing.touched || routing.dirty">
              <span *ngIf="routing.touched && routing.errors?.['minlength']">
                Valid Routing Number is required
              </span>
            </div>
          </div>
          <div class="field">
            <label for="bankAccount" class="{setLabelClassName(bankAccountError)}">
              Bank Account Number
            </label>
            <input
              type="number"
              name="bankAccount"
              #bankAccount="ngModel"
              [(ngModel)]="formValues.bankAccount"
              minlength="10"
              maxlength="10"
            />
            <div *ngIf="bankAccount.touched || bankAccount.dirty">
              <span *ngIf="bankAccount.touched && bankAccount.errors?.['minlength']">
                Valid Bank Account Number is required
              </span>
            </div>
          </div>
          <div class="field">
            <label for="confirmBankAccount" class="{setLabelClassName(confirmBankAccountError)}">
              Confirm Bank Account Number
            </label>
            <input
              type="number"
              name="confirmBankAccount"
              #confirmBankAccount="ngModel"
              [(ngModel)]="formValues.confirmBankAccount"
              minlength="10"
              maxlength="10"
            />
            <div *ngIf="confirmBankAccount.touched || confirmBankAccount.dirty">
              <span *ngIf="confirmBankAccount.touched && confirmBankAccount.errors?.['minlength']">
                Valid Confirm Bank Account Number is required
              </span>
              <span class="{setSpanClassName(confirmBankAccountMismatch)}">
                Confirm Bank Account Number must match Bank Account Number
              </span>
            </div>
          </div>
        </div>
        <div *ngIf="formValues.debitCard">
          <div class="field">
            <label for="card" class="{setLabelClassName(cardError)}"> Card Number </label>
            <input
              type="number"
              name="card"
              #card="ngModel"
              [(ngModel)]="formValues.card"
              minlength="16"
              maxlength="16"
            />
            <div *ngIf="card.touched || card.dirty">
              <span *ngIf="card.touched && card.errors?.['minlength']">
                Valid Card Number is required
              </span>
            </div>
          </div>
          <div class="field">
            <label for="nameOnCard" class="{setLabelClassName(nameOnCardError)}">
              Name on Card
            </label>
            <input
              type="text"
              name="nameOnCard"
              #nameOnCard="ngModel"
              [(ngModel)]="formValues.nameOnCard"
              minlength="1"
            />
            <div *ngIf="nameOnCard.touched || nameOnCard.dirty">
              <span *ngIf="nameOnCard.touched && nameOnCard.errors?.['minlength']">
                Valid Name is required
              </span>
            </div>
          </div>
          <div class="half-field">
            <div class="field">
              <label for="expirationDate" class="{setLabelClassName(expirationDateError)}">
                Expiration Date
              </label>
              <input
                type="date"
                name="expirationDate"
                #expirationDate="ngModel"
                [(ngModel)]="formValues.expirationDate"
              />
              <div *ngIf="expirationDate.touched || expirationDate.dirty">
                <span *ngIf="expirationDate.touched && expirationDate.errors?.['required']">
                  Valid Expiration Date is required
                </span>
              </div>
            </div>
            <div class="field">
              <label class="{setLabelClassName(cvvError)}" for="cvv"> CVV </label>
              <input type="number" name="cvv" #cvv="ngModel" [(ngModel)]="formValues.cvv" />
              <div *ngIf="cvv.touched || cvv.dirty">
                <span class="{setSpanClassName(cvvError)}"> Valid CVV is required </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="split-right">
        <div>
          <p>Where can I find the routing and account number?</p>
          <img
            class=""
            className_="{checking === 'on' ? 'check' : 'cvv'}"
            src=""
            src_="{checking === 'on' ? check : cvv}"
            alt=""
            alt_="routing and account number"
          />
        </div>
      </div>
    </div>
    <div className="submit">
      <input type="button" value="MAKE PAYMENT" (click)="onSubmit()" />
    </div>
  </form>
</div>

// source-react/src/components/Form/Form.tsx
import { useState, useMemo, useCallback } from 'react'
import check from '../../assets/check.png'
import cvv from '../../assets/cvv.png'
import { Checking } from '../Checking/Checking'
import { DebitCard } from '../DebitCard/DebitCard'
import { validate, ValidationKey } from '../../utils/validations'
import { setLabelClassName, setSpanClassName } from '../../utils/className'
import './Form.css'

type ValuesKey =
  | 'loanAccount'
  | 'checking'
  | 'debitCard'
  | 'routing'
  | 'bankAccount'
  | 'confirmBankAccount'
  | 'card'
  | 'nameOnCard'
  | 'expirationDate'
  | 'cvv'

type Values = {
  loanAccount: string
  checking: string
  debitCard: string
  routing: string
  bankAccount: string
  confirmBankAccount: string
  card: string
  nameOnCard: string
  expirationDate: string
  cvv: string
}

type Errors = {
  loanAccount: boolean
  routing: boolean
  bankAccount: boolean
  confirmBankAccount: boolean
  confirmBankAccountMismatch: boolean
  card: boolean
  nameOnCard: boolean
  expirationDate: boolean
  cvv: boolean
}

const isValuesKey = (key: string): key is ValuesKey => {
  return [
    'loanAccount',
    'checking',
    'debitCard',
    'routing',
    'bankAccount',
    'confirmBankAccount',
    'card',
    'nameOnCard',
    'expirationDate',
    'cvv'
  ].includes(key)
}

const isValidationKey = (key: string): key is ValidationKey => {
  return [
    'loanAccount',
    'routing',
    'bankAccount',
    'confirmBankAccount',
    'card',
    'nameOnCard',
    'expirationDate',
    'cvv'
  ].includes(key)
}

export function Form() {
  const initialValues = useMemo<Values>(
    () => ({
      loanAccount: '',
      checking: 'on',
      debitCard: '',
      routing: '',
      bankAccount: '',
      confirmBankAccount: '',
      card: '',
      nameOnCard: '',
      expirationDate: '',
      cvv: ''
    }),
    []
  )
  const [values, setValues] = useState<Values>(initialValues)
  const initialErrors = useMemo<Errors>(
    () => ({
      loanAccount: false,
      routing: false,
      bankAccount: false,
      confirmBankAccount: false,
      confirmBankAccountMismatch: false,
      card: false,
      nameOnCard: false,
      expirationDate: false,
      cvv: false
    }),
    []
  )
  const [errors, setErrors] = useState<Errors>(initialErrors)

  const onChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const { id, value } = event.target
      if (isValuesKey(id)) {
        if (id === 'checking') {
          setValues({ ...values, checking: 'on', debitCard: '' })
        } else if (id === 'debitCard') {
          setValues({ ...values, debitCard: 'on', checking: '' })
        } else {
          setValues({ ...values, [id]: value })
        }
      }
    },
    [values]
  )

  const onBlur = useCallback(
    (event: React.FocusEvent<HTMLInputElement>) => {
      const { id, value } = event.target

      if (isValidationKey(id) && !validate[id](value)) {
        setErrors({ ...errors, [id]: true })
      } else {
        setErrors({ ...errors, [id]: false })
      }
    },
    [errors]
  )

  const onSubmit = useCallback(() => {
    const {
      loanAccount,
      checking,
      routing,
      bankAccount,
      confirmBankAccount,
      card,
      nameOnCard,
      expirationDate,
      cvv
    } = values
    let newErrors = {
      ...initialErrors,
      loanAccount: !validate.loanAccount(loanAccount)
    }
    let request

    if (checking === 'on') {
      newErrors = {
        ...newErrors,
        routing: !validate.routing(routing),
        bankAccount: !validate.bankAccount(bankAccount),
        confirmBankAccount: !validate.confirmBankAccount(confirmBankAccount),
        confirmBankAccountMismatch: bankAccount !== confirmBankAccount
      }
      request = {
        loanAccount,
        routing,
        bankAccount
      }
    } else {
      newErrors = {
        ...newErrors,
        card: !validate.card(card),
        nameOnCard: !validate.nameOnCard(nameOnCard),
        expirationDate: !validate.expirationDate(expirationDate),
        cvv: !validate.cvv(cvv)
      }
      request = {
        loanAccount,
        card,
        nameOnCard,
        expirationDate,
        cvv
      }
    }
    console.log('request:', request)
    console.log('newErrors:', newErrors)
    if (Object.values(newErrors).includes(true)) {
      setErrors(newErrors)
      return
    }
    // setErrors(initialErrors)
    // there would be a try/catch with a fetch request here to send the form data to the server
  }, [values, initialErrors])

  const { loanAccount, checking, debitCard } = values
  const { loanAccount: loanAccountError } = errors

  return (
    <div className="Form">
      <h2>One-time Loan Payment</h2>
      <p>Fill out the form below to complete your payment.</p>
      <form>
        <div className="field">
          <label
            className={setLabelClassName(loanAccountError)}
            htmlFor="loanAccount"
          >
            Loan Account Number
          </label>
          <input
            type="number"
            id="loanAccount"
            value={loanAccount}
            onChange={onChange}
            onBlur={onBlur}
          />
          <span className={setSpanClassName(loanAccountError)}>
            Valid Loan Account Number is required
          </span>
        </div>
        <div className="split-container">
          <div className="split-left">
            <div className="field">
              <label htmlFor="accountType">Type of Account</label>
              <div className="radio-group">
                <input
                  type="radio"
                  id="checking"
                  onChange={onChange}
                  checked={checking === 'on'}
                />
                <label htmlFor="checking">Checking</label>
                <input
                  type="radio"
                  id="debitCard"
                  onChange={onChange}
                  checked={debitCard === 'on'}
                />
                <label htmlFor="debitCard">Debit Card</label>
              </div>
            </div>
            {checking === 'on' ? (
              <Checking
                values={values}
                errors={errors}
                onChange={onChange}
                onBlur={onBlur}
              />
            ) : (
              <DebitCard
                values={values}
                errors={errors}
                onChange={onChange}
                onBlur={onBlur}
              />
            )}
          </div>
          <div className="split-right">
            <Information checking={checking} />
          </div>
        </div>
        <div className="submit">
          <input type="button" value="MAKE PAYMENT" onClick={onSubmit} />
        </div>
      </form>
    </div>
  )
}

function Information({ checking }: { checking: string }) {
  return (
    <div>
      {checking === 'on' ? (
        <p>Where can I find the routing and account number?</p>
      ) : (
        <p>Where can I find the cvv number?</p>
      )}
      <img
        className={checking === 'on' ? 'check' : 'cvv'}
        src={checking === 'on' ? check : cvv}
        alt="routing and account number"
      />
    </div>
  )
}
